# rana-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rana
      class: unnati
  template:
    metadata:
      labels:
        app: rana
        class: unnati
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo
          args:
            - "-text=Hello from rana!"
          ports:
            - containerPort: 5678
