# rushi-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rushi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rushi
      class: unnati
  template:
    metadata:
      labels:
        app: rushi
        class: unnati
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo
          args:
            - "-text=Hello from rushi!"
          ports:
            - containerPort: 5678
